### ISSUE TITLE
'run_combine_als' error 'Dataframe' object has no attribute 'y_nt'

### ISSUE THREAD

**Issue by maxshafer** [annnic/cichlid-analysis#10]
Here's the error that 'run_combine_als' spits out, I couldn't make sense of the file's it references, but it seems to be trying to access 'y_nt' after it has already been removed?

```
/usr/local/bin/python3.7 /Users/maxwellshafer/cichlid-analysis/cichlidanalysis/analysis/run_combine_als.py
objc[12034]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9fcb03c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x132de1f50). One of the two will be used. Which one is undefined.
loaded file FISH20210108_c1_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210108_c2_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210108_c3_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210108_c4_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210108_c5_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210108_c6_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210115_c1_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210115_c2_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210115_c3_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210115_c4_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210115_c5_r0_Telmatochromis-vittatus_su_als.csv
loaded file FISH20210115_c6_r0_Telmatochromis-vittatus_su_als.csv
All als.csv files loaded
time to load tracks 341.2032651901245
loaded file FISH20210108_c1_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210108_c2_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210108_c3_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210108_c4_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210108_c5_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210108_c6_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210115_c1_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210115_c2_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210115_c3_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210115_c4_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210115_c5_r0_Telmatochromis-vittatus_su_meta.csv
loaded file FISH20210115_c6_r0_Telmatochromis-vittatus_su_meta.csv
time to load tracks 525.7627079486847
<class 'pandas.core.frame.DataFrame'>
Int64Index: 66363874 entries, 0 to 5527185
Data columns (total 9 columns):
 #   Column         Dtype         
---  ------         -----         
 0   tv_ns          float64       
 1   speed_mm       float64       
 2   x_nt           float64       
 3   y_nt           float64       
 4   FishID         object        
 5   ts             datetime64[ns]
 6   time_of_day_m  int64         
 7   daynight       object        
 8   movement       float64       
dtypes: datetime64[ns](1), float64(5), int64(1), object(2)
memory usage: 4.9+ GB
removed y_nt
removed x_nt
removed tv_ns
Traceback (most recent call last):
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/analysis/run_combine_als.py", line 346, in <module>
    spd_vs_y(meta, fish_tracks, fish_tracks_30m, fish_IDs, rootdir)
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/plotting/position_plots.py", line 49, in spd_vs_y
    vertical_pos_30m = fish_tracks_30m[fish_tracks_30m.FishID == fish].y_nt
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'y_nt'

Process finished with exit code 1
```

**Comment by annnic** [comment]
Some scripts are still using y_nt instead of vertical position (normalised 0 to 1 between bottom and top). Need to remove dependency on y_nt in position plots
