### ISSUE TITLE
'retracking' doesn't work on Cyplep c4 r0

### ISSUE THREAD

**Issue by maxshafer** [annnic/cichlid-analysis#12]
'retracking' is working for other folders (including c4 r1) but for some reason errors out for this folder? 

```
/usr/local/bin/python3.7 /Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/retracking.py
Update background? y/n: 
n
Track videos? y/n: 
y
Track all videos? y/n: 
y
objc[16560]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9fcb03c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12da74f50). One of the two will be used. Which one is undefined.
Didn't find remade background, will use original background in camera folder
Track with another roi? y/n: 
y
/Volumes/BZ/Scientific Data/RG-AS04-Data01/Cichlid_sleep_videos/FISH20200930_LT_Cyplep/20200930_c4_Cyprichromis-leptosoma/roi_file.yaml
{'cam_ID': '19463356', 'roi_0': (22, 81, 640, 880), 'roi_1': (642, 67, 608, 864)}
/Volumes/BZ/Scientific Data/RG-AS04-Data01/Cichlid_sleep_videos/FISH20200930_LT_Cyplep/20200930_c4_Cyprichromis-leptosoma/FISH20200930_c4_r0_Cyprichromis-leptosoma_sm/roi_file.yaml
{'cam_ID': 'na', 'roi_0': (6, 81, 615, 794)}
tracking /Volumes/BZ/Scientific Data/RG-AS04-Data01/Cichlid_sleep_videos/FISH20200930_LT_Cyplep/20200930_c4_Cyprichromis-leptosoma/FISH20200930_c4_r0_Cyprichromis-leptosoma_sm/20200930-120320_0_roi-0.mp4
Traceback (most recent call last):
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/retracking.py", line 138, in <module>
    area_size=100)
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/offline_tracker.py", line 54, in tracker
    frameDelta_full = cv2.absdiff(background_full, gray)
cv2.error: OpenCV(4.4.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-4jcifzim/opencv/modules/core/src/arithm.cpp:669: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'


Process finished with exit code 1
```

**Comment by annnic** [comment]
Found the issue but unsure of what caused the video roi to be off on the video background. Fixed for this video but let me know of others that do this.
