### ISSUE TITLE
bug in run_combine_als

### ISSUE THREAD

**Issue by annnic** [annnic/cichlid-analysis#29]
On Neohel

...
loaded file FISH20210526_c2_r0_Neolamprologus-helianthus_su_meta.csv
Traceback (most recent call last):
  File "/Users/annikanichols/Documents/cichlid-analysis/cichlidanalysis/analysis/run_combine_als.py", line 69, in <module>
    fish_tracks['time_of_day_m'] = fish_tracks.ts.apply(lambda row: int(str(row)[11:16][:-3]) * 60 + int(str(row)[11:16][-2:]))
  File "/Users/annikanichols/Documents/cichlid-analysis/.venv/lib/python3.7/site-packages/pandas/core/series.py", line 4213, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "/Users/annikanichols/Documents/cichlid-analysis/cichlidanalysis/analysis/run_combine_als.py", line 69, in <lambda>
    fish_tracks['time_of_day_m'] = fish_tracks.ts.apply(lambda row: int(str(row)[11:16][:-3]) * 60 + int(str(row)[11:16][-2:]))
ValueError: invalid literal for int() with base 10: ''

Process finished with exit code 1

**Comment by maxshafer** [comment]
For Neofal - different but is also being run when a subset of the als files are new (it stops at the new one, c5r0 and c5r1 were QA'd):

/usr/local/bin/python3.7 /Users/maxwellshafer/cichlid-analysis/cichlidanalysis/analysis/run_combine_als.py
2021-06-08 09:46:44.913 Python[18915:624514] WARNING: <NSOpenPanel: 0x7f808e4cce50> running implicitly; please run panels using NSSavePanel rather than NSApplication.
loaded file FISH20210526_c3_r0_Neolamprologus-falcicula_su_als.csv
loaded file FISH20210526_c3_r1_Neolamprologus-falcicula_su_als.csv
loaded file FISH20210526_c4_r0_Neolamprologus-falcicula_su_als.csv
Traceback (most recent call last):
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/analysis/run_combine_als.py", line 47, in <module>
    fish_tracks = load_als_files(rootdir)
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/io/tracks.py", line 168, in load_als_files
    data_s = pd.read_csv(os.path.join(folder, file), sep=',')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 458, in _read
    data = parser.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 1196, in read
    ret = self._engine.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 2155, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 5 fields in line 4634616, saw 7


Process finished with exit code 1

**Comment by annnic** [comment]
Problem with: 
fish_tracks.iloc[9949731]
tv_ns                                                   NaN
speed_mm                                         NaN
x_nt                                                    NaN
y_nt                                                    NaN
FishID      FISH20210519_c2_r0_Neolamprologus-helianthus_su
ts                                                      NaT

Only one time point. (last time point for this fish)

Fixed with:
# drop "not a time" columns
print("dropping indices as they don't have a time {}".format(fish_tracks[np.isnat(fish_tracks.ts)].index))
fish_tracks = fish_tracks.drop(fish_tracks[np.isnat(fish_tracks.ts)].index)
in load_als_files

**Comment by annnic** [comment]
> For Neofal - different but is also being run when a subset of the als files are new (it stops at the new one, c5r0 and c5r1 were QA'd):This seems to have been a problem with just that one file. Remade it and now it works

**Comment by annnic** [comment]
Fixed the 2 problematic als files by rerunning run_fish_als, not sure why this happened in the first place. If this happens again it will cause the same error and I can follow up.

![image](https://user-images.githubusercontent.com/6535283/121219375-ea2caf00-c883-11eb-8057-ee2841ca9da5.png)

Re-running als fixed it (note that it is much shorter)

![image](https://user-images.githubusercontent.com/6535283/121219551-1b0ce400-c884-11eb-87b7-fa49b6651d78.png)
