### ISSUE TITLE
Retracking with new background

### ISSUE THREAD

**Issue by annnic** [annnic/cichlid-analysis#30]
/Users/annikanichols/Documents/cichlid-analysis/.venv/bin/python3 /Users/annikanichols/Documents/cichlid-analysis/cichlidanalysis/tracking/retracking.py
Update background? y/n: 
n
Track videos? y/n: 
y
Track all videos? y/n: 
y
Track with another roi? y/n: 
y
/Volumes/RG-AS04-Data01/Cichlid_sleep_videos/FISH20200727_LT_Neopul-daffodil/20200727_cam_1/roi_file.yaml
{'cam_ID': '19463146', 'roi_0': (605, 185, 480, 672)}
/Volumes/RG-AS04-Data01/Cichlid_sleep_videos/FISH20200727_LT_Neopul-daffodil/20200727_cam_1/FISH20200727_c1_r0_Neolamprologus-pulcher-daffodil_sf/roi_file.yaml
{'cam_ID': 'na', 'roi_0': (12, 91, 438, 566)}
tracking with background ['20200727-110529_0_roi-0_per90_background.png']
tracking /Volumes/RG-AS04-Data01/Cichlid_sleep_videos/FISH20200727_LT_Neopul-daffodil/20200727_cam_1/FISH20200727_c1_r0_Neolamprologus-pulcher-daffodil_sf/20200727-110529_0_roi-0.mp4
Traceback (most recent call last):
  File "/Users/annikanichols/Documents/cichlid-analysis/cichlidanalysis/tracking/retracking.py", line 158, in <module>
    area_size=100)
  File "/Users/annikanichols/Documents/cichlid-analysis/cichlidanalysis/tracking/offline_tracker.py", line 54, in tracker
    frameDelta_full = cv2.absdiff(background_full, gray)
cv2.error: OpenCV(4.4.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-ucld1hvm/opencv/modules/core/src/arithm.cpp:669: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'

Process finished with exit code 1

**Comment by annnic** [comment]
Needed to not crop the background if using a newly made background as it is already cropped
