### ISSUE TITLE
Issue with fish that was tracked with previous version of the retracking software

### ISSUE THREAD

**Issue by maxshafer** [annnic/cichlid-analysis#35]
This applies to:

/Volumes/BZ/Scientific Data/RG-AS04-Data01/Cichlid_sleep_videos/FISH20200907_LT_Neogra/20200907_c6_Neolamprologus-gracilis/FISH20200907_c6_r0_Neolamprologus-gracilis_sm

And the following error when running 'helpers.py':

`/usr/local/bin/python3.7 /Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/helpers.py
Correct new tracks? y/n: 
y
What is the date tag for the new tracks? YYYYMMDD: 
20201030
2022-01-24 14:18:54.511 Python[15945:1150266] WARNING: <NSOpenPanel: 0x7f7f6997d0b0> running implicitly; please run panels using NSSavePanel rather than NSApplication.
updating timestamps of 20200907-172825_0_roi-0_tracks_20201030_Thresh_35_Area_100_roi-0.csv and adding exclude tag to 20200907-172825_0_roi-0.csv
updating timestamps of 20200907-182820_1_roi-0_tracks_20201030_Thresh_35_Area_100_roi-0.csv and adding exclude tag to 20200907-182820_1_roi-0.csv
Traceback (most recent call last):
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/helpers.py", line 230, in <module>
    correct_tags(date_tag, rootdir)
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/helpers.py", line 206, in correct_tags
    update_csvs(os.path.join(vid_directory, orig_file), os.path.join(vid_directory, new_f))
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/helpers.py", line 157, in update_csvs
    copy_timestamps(orig_csv_path, new_csv_path)
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/helpers.py", line 130, in copy_timestamps
    _, track_single_orig = load_track(orig_csv_path_i)
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/io/tracks.py", line 12, in load_track
    track_internal = np.genfromtxt(csv_file_path, delimiter=',')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 194, in open
    ds = DataSource(destpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 251, in __init__
    self._destpath = os.path.abspath(destpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 45] Operation not supported

Process finished with exit code 1`

**Comment by annnic** [comment]
Runs perfectly on my computer. Seemed to be an issue with loading the csv with: track_internal = np.genfromtxt(csv_file_path, delimiter=',')
Perhaps a connection issue? If this happens again I can look at it again.
